### ISSUE TITLE
Fix bug where game crashes when given same destination as origin

### ISSUE THREAD

**Issue by mononoken** [mononoken/chess#27]
I noticed when making the following moves the game crashes:
d2 -> d4
d7 -> d7

Gives:
```bash
/Users/***/projects/top/chess/lib/position.rb:119:in `==': undefined method `file_index' for nil:NilClass (NoMethodError)

    other.file_index == file_index && other.rank_index == rank_index
         ^^^^^^^^^^^
        from /Users/***/projects/top/chess/lib/movement.rb:40:in `==='
        from /Users/***/projects/top/chess/lib/movement.rb:40:in `any?'
        from /Users/***/projects/top/chess/lib/movement.rb:40:in `valid_destination?'
        from /Users/***/projects/top/chess/lib/movement.rb:12:in `valid_destination?'
        from /Users/***/projects/top/chess/lib/position.rb:45:in `valid_destination?'
        from /Users/***/projects/top/chess/lib/chess_controller.rb:89:in `block in player_destination'
        from /Users/***/projects/top/chess/lib/chess_controller.rb:85:in `loop'
        from /Users/***/projects/top/chess/lib/chess_controller.rb:85:in `player_destination'
        from /Users/***/projects/top/chess/lib/chess_controller.rb:60:in `player_movement'
        from /Users/***/projects/top/chess/lib/chess_controller.rb:44:in `run_round'
        from /Users/***/projects/top/chess/lib/chess_controller.rb:36:in `run_rounds'
        from /Users/***/projects/top/chess/lib/chess_controller.rb:31:in `play'
        from /Users/***/projects/top/chess/lib/chess_controller.rb:9:in `play'
        from lib/main.rb:17:in `<main>'
```

Does not happen for every duplicate move. For example starting the game with d2 -> d2 gives the correct warning without crashing the game.

**Comment by mononoken** [comment]
Error seems to stem from `Movement#valid_destinations`, which returns an array of `Position` objects, sometimes containing `nil`.

This leads to `nil` being allowed to be passed in creating a Movement, which should not happen with this CLI.

**Comment by mononoken** [comment]
This bug was being caused by `PassantMovement#valid_passant_destinations`. The method was setup so that a conditional would return `nil` and populate an array with `nil`. This array would be concatenated with other destination arrays later. It was fixed by making it so that it returns an empty array instead.

bd229bbdb7208166336ca61d40baf113ed914afa fixes
